import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import vm from 'node:vm';
import {createMilestoneStore,validateMilestone,MILESTONE_LIMIT} from '../lib/milestones.js';
process.env.DSH_NOTIFY_ALL_DRY_RUN='1';
const {apply,DEFAULTS}=await import('../lib/index.js');
const A='session-00000000-0000-4000-8000-000000000001',B='session-00000000-0000-4000-8000-000000000002',C='session-00000000-0000-4000-8000-000000000003';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'dsh-milestones-'));
let passed=0;const check=(label,fn)=>{fn();passed++;console.log('PASS '+label);};
const flush=()=>new Promise(resolve=>setImmediate(resolve)), plain=value=>JSON.parse(JSON.stringify(value));
const cleanups=[];
try {
 const file=path.join(temp,'metadata.json'),saved=createMilestoneStore(file);
 saved.set({sessionId:A,turn:40,seq:1234,name:'  交付验收  '});saved.set({sessionId:A,turn:2,name:'需求确认'});saved.set({sessionId:B,turn:40,name:'另一会话'});
 check('milestones are sorted by real turn, independent of displayed rail index',()=>assert.deepEqual(saved.snapshot(A).milestones.map(x=>x.turn),[2,40]));
 check('names are trimmed and conversations with the same turn stay isolated',()=>{assert.equal(saved.snapshot(A).milestones[1].name,'交付验收');assert.equal(saved.snapshot(B).milestones[0].name,'另一会话');});
 const revision=saved.snapshot(A).revision;saved.set({sessionId:A,turn:40,seq:1234,name:'交付验收'});
 check('repeated saving is idempotent',()=>assert.equal(saved.snapshot(A).revision,revision));
 saved.set({sessionId:A,turn:40,seq:1234,name:'验收通过'});
 check('rename changes one milestone without duplicates',()=>{assert.equal(saved.snapshot(A).milestones.length,2);assert.equal(saved.snapshot(A).milestones[1].name,'验收通过');});
 const reloaded=createMilestoneStore(file);
 check('names and sequence anchors persist across restart',()=>assert.deepEqual(reloaded.snapshot(A).milestones,saved.snapshot(A).milestones));
 check('restart has a fresh response generation',()=>assert.notEqual(reloaded.snapshot(A).generation,saved.snapshot(A).generation));
 reloaded.set({sessionId:A,turn:40},true);
 check('removing one milestone preserves other turns and conversations',()=>{assert.deepEqual(reloaded.snapshot(A).milestones.map(x=>x.turn),[2]);assert.equal(reloaded.snapshot(B).milestones.length,1);});
 for(const input of [{sessionId:'not-a-session',turn:0,name:'a'},{sessionId:A,turn:-1,name:'a'},{sessionId:A,turn:1.5,name:'a'},{sessionId:A,turn:Number.MAX_SAFE_INTEGER+1,name:'a'},{sessionId:A,turn:0,seq:-1,name:'a'},{sessionId:A,turn:0,name:'   '},{sessionId:A,turn:0,name:'a'.repeat(81)},{sessionId:A,turn:0,name:'x\ny'},{sessionId:A,turn:0,name:'x\u202ey'}]) {
   check('invalid metadata is rejected: '+JSON.stringify(input),()=>assert.throws(()=>validateMilestone(input)));
 }
 const bounded=createMilestoneStore(path.join(temp,'bounded.json'));
 for(let turn=0;turn<MILESTONE_LIMIT;turn++)bounded.set({sessionId:A,turn,name:'M '+turn});
 check('per-conversation capacity is bounded',()=>assert.throws(()=>bounded.set({sessionId:A,turn:MILESTONE_LIMIT,name:'overflow'})));
 bounded.set({sessionId:A,turn:0,name:'renamed'});bounded.set({sessionId:A,turn:1},true);bounded.set({sessionId:A,turn:MILESTONE_LIMIT,name:'space reused'});
 check('rename and removal still work at the storage limit',()=>assert.equal(bounded.snapshot(A).milestones.length,MILESTONE_LIMIT));
 const broken=path.join(temp,'broken.json');fs.writeFileSync(broken,JSON.stringify({version:1,rows:[null,{sessionId:A,turn:3,name:'valid'},{sessionId:A,turn:'4',name:'invalid'}]}));
 check('malformed rows do not discard valid persisted milestones',()=>assert.equal(createMilestoneStore(broken).snapshot(A).milestones.length,1));
 const failed=path.join(temp,'missing','store.json'),transaction=createMilestoneStore(failed);
 assert.throws(()=>transaction.set({sessionId:A,turn:1,name:'cannot write'}));
 check('failed persistence never publishes a phantom milestone',()=>assert.equal(transaction.snapshot(A).milestones.length,0));

 const routes=new Map(),events=new Map(),config={...DEFAULTS},sessions=new Map([A,B].map(id=>[id,{id,running:true}]));
 let resolveLookup;
 const effect=fn=>{const off=fn();if(typeof off==='function')cleanups.push(off);return off;};
 const ctx={fiber:{},effect,get:key=>({profileContext:{home:temp},sessions:{get:id=>sessions.get(id)},sessionQuery:{listSessions:()=>new Promise(resolve=>{resolveLookup=resolve;})}})[key],
   connection:{fetch:{register:row=>{routes.set(row.path,row);return()=>routes.delete(row.path);}}},
   on:(key,fn)=>{events.set(key,fn);const off=()=>events.delete(key);cleanups.push(off);return off;},inject:()=>{}};
 apply(ctx,config);
 const api=async(body,id=A,signal)=>{const res=await routes.get('/api/dsh-notify-all/milestones').fetch(new Request('http://localhost/api/dsh-notify-all/milestones?sessionId='+id,{method:body?'POST':'GET',...(body?{body:JSON.stringify(body)}:{}),signal}));return{code:res.status,data:await res.json()};};
 const dir=path.join(temp,'dsh-notify-all'),badgeBefore=fs.readFileSync(path.join(dir,'badge.json'),'utf8'),logBefore=fs.readFileSync(path.join(dir,'log.txt'),'utf8');
 const created=await api({op:'set',sessionId:A,turn:5,seq:100,name:'完成部署'});
 check('authenticated carrier exposes GET and POST milestone route',()=>assert.deepEqual(routes.get('/api/dsh-notify-all/milestones').methods,['GET','POST']));
 check('Host saves named milestone without touching Session running state',()=>{assert.equal(created.code,200);assert.equal(created.data.milestones[0].name,'完成部署');assert.equal(sessions.get(A).running,true);});
 const listed=await api();
 check('Host returns persisted metadata for exactly the queried conversation',()=>{assert.equal(listed.data.sessionId,A);assert.equal(listed.data.milestones.length,1);});
 check('milestone actions leave unread and badge state unchanged',()=>{assert.equal(fs.readFileSync(path.join(dir,'badge.json'),'utf8'),badgeBefore);assert.ok(!fs.existsSync(path.join(dir,'state.json')));});
 check('milestone actions invoke no Toast',()=>assert.equal(fs.readFileSync(path.join(dir,'log.txt'),'utf8'),logBefore));
 const invalidOp=await api({op:'clear',sessionId:A,turn:5}),invalidId=await api(undefined,'../other');
 check('invalid operation cannot mutate metadata',()=>assert.equal(invalidOp.code,400));
 check('GET rejects an invalid session identifier',()=>assert.equal(invalidId.code,400));
 config.enabled=false;
 const disabled=await api({op:'remove',sessionId:A,turn:5});
 check('disabled plugin rejects new milestone mutations',()=>assert.equal(disabled.code,400));config.enabled=true;
 const absent=api({op:'set',sessionId:C,turn:1,name:'unknown'});await flush();resolveLookup([]);
 const absentResult=await absent;check('unknown conversations cannot create milestones',()=>assert.equal(absentResult.code,400));
 const controller=new AbortController(),cancelled=api({op:'set',sessionId:C,turn:1,name:'cancelled'},C,controller.signal);await flush();controller.abort();
 const cancelledResult=await cancelled;check('cancelled lookups cannot publish late milestones',()=>assert.equal(cancelledResult.code,400));resolveLookup([{header:{id:C}}]);await flush();
 const afterCancel=await api();check('late provider results do not bypass cancellation',()=>assert.equal(afterCancel.data.milestones.length,1));

 let exported;const pending=[],intervals=new Set(),clientCleanups=[],sourceListeners=new Set(),connectionEvents=new Map();
 const source=initial=>{let value=initial;const local=new Set();return{getSnapshot:()=>value,subscribe:fn=>{local.add(fn);sourceListeners.add(fn);return()=>{local.delete(fn);sourceListeners.delete(fn);};},set(next){value=next;for(const fn of [...local])fn();}};};
 const outline=source([{turn:40,seq:400},{turn:2,seq:20},null,{turn:0,seq:-1}]),chat=source({navigation:{items:()=>[{turn:2},{turn:99}]}});
 const bind=id=>({key:id,hooks:{chat},keyedHooks:{projection:()=>outline}}),current=source(bind(A)),form=source({value:{enabled:true}});
 const sandbox={window:{__ModuleLoader__:{load:row=>{exported=row.factory(id=>{assert.equal(id,'react');return {createElement:(type,props,...children)=>({type,props,children}),useSyncExternalStore:(_subscribe,get)=>get()};});}}},document:{hidden:false},setTimeout,clearTimeout,AbortController,
   setInterval:fn=>{intervals.add(fn);return fn;},clearInterval:fn=>intervals.delete(fn),fetch:(url,init)=>new Promise(resolve=>pending.push({id:new URL('http://localhost'+url).searchParams.get('sessionId'),body:init.body?JSON.parse(init.body):undefined,resolve})),Date,Math};
 vm.runInNewContext(fs.readFileSync(new URL('../lib/client.js',import.meta.url),'utf8'),sandbox);
 check('public sources reproduce native outline + loaded-turn ordering',()=>assert.deepEqual(plain(exported.milestoneTurns(bind(A))),[{turn:2,seq:20},{turn:40,seq:400},{turn:99}]));
 check('sequence mismatch does not highlight a reused anchor',()=>assert.equal(exported.milestoneMatches({turn:2,seq:10},{turn:2,seq:20}),false));
 const clientCtx={uiSession:{current},effect:fn=>{const off=fn();if(typeof off==='function')clientCleanups.push(off);},on:(key,fn)=>connectionEvents.set(key,fn)};
 const store=exported.milestoneStore(clientCtx,form,key=>key);
 const reply=(req,id,revision,milestones=[],generation='host')=>req.resolve({ok:true,json:async()=>({sessionId:id,revision,generation,milestones})});
 const first=pending.shift();current.set(bind(B));const second=pending.shift();
 reply(second,B,0);await flush();reply(first,A,1,[{sessionId:A,turn:2,name:'wrong conversation'}]);await flush();
 check('late previous-conversation response cannot mark current rail',()=>{assert.equal(store.getSnapshot().sessionId,B);assert.equal(store.getSnapshot().milestones.length,0);});
 current.set(bind(A));reply(pending.shift(),A,1);await flush();
 store.edit({turn:40,seq:400});const writing=store.mutate({turn:40,seq:400},'关键交付');const write=pending.shift();
 check('saving carries real turn and outline sequence, never rail index',()=>assert.deepEqual(write.body,{op:'set',sessionId:A,turn:40,seq:400,name:'关键交付'}));
 const duplicate=store.mutate({turn:40,seq:400},'duplicate');await duplicate;
 check('duplicate clicks cannot race an in-progress save',()=>assert.equal(pending.length,0));
 reply(write,A,3,[{sessionId:A,turn:40,seq:400,name:'关键交付'}]);await writing;
 check('successful saving closes the editor and publishes highlight state',()=>{assert.equal(store.getSnapshot().dialog,null);assert.equal(store.getSnapshot().milestones[0].name,'关键交付');});
 const stale=store.refresh();reply(pending.shift(),A,2);await stale;
 check('older polling response cannot undo a saved milestone',()=>assert.equal(store.getSnapshot().milestones.length,1));
 store.edit({turn:40,seq:400});
 check('renaming opens the existing name',()=>assert.equal(store.getSnapshot().dialog.name,'关键交付'));
 await store.mutate({turn:40,seq:400},'   ');
 check('blank names are rejected inline without a Host mutation',()=>{assert.equal(pending.length,0);assert.equal(store.getSnapshot().dialog.error,'milestoneInvalid');});
 store.close();const removing=store.mutate({turn:40,seq:400},'',true);reply(pending.shift(),A,4);await removing;
 check('cancelling a milestone restores unmarked state without opening another UI',()=>{assert.equal(store.getSnapshot().dialog,null);assert.equal(store.getSnapshot().milestones.length,0);});
 store.edit({turn:2,seq:20});const slow=store.mutate({turn:2,seq:20},'late');const oldWrite=pending.shift();current.set(bind(B));reply(pending.shift(),B,4);await flush();reply(oldWrite,A,5,[{sessionId:A,turn:2,name:'late'}]);await slow;
 check('switching during a save closes the editor and ignores the old highlight',()=>{assert.equal(store.getSnapshot().sessionId,B);assert.equal(store.getSnapshot().dialog,null);assert.equal(store.getSnapshot().milestones.length,0);});
 form.set({value:{enabled:false}});
 check('disabling plugin removes its milestone UI state',()=>{assert.equal(store.getSnapshot().enabled,false);assert.equal(store.getSnapshot().dialog,null);});
 form.set({value:{enabled:true}});reply(pending.shift(),B,0,[],'restarted');await flush();
 check('enabling or restarting restores fresh response ordering',()=>assert.equal(store.getSnapshot().enabled,true));
 const inFlight=store.refresh(),last=pending.shift();clientCleanups.reverse().forEach(fn=>fn());reply(last,B,6,[{sessionId:B,turn:2,name:'after unload'}]);await inFlight;
 check('unload removes polling and every source subscription',()=>{assert.equal(intervals.size,0);assert.equal(sourceListeners.size,0);});
 check('late responses after unload are ignored',()=>assert.equal(store.getSnapshot().milestones.length,0));
 const sourceCode=fs.readFileSync(new URL('../lib/client.js',import.meta.url),'utf8');
 check('no milestone directory, header button or gold styling remains',()=>{assert.ok(!sourceCode.includes('dna-milestone-header'));assert.ok(!sourceCode.includes('dna-milestone-list'));assert.ok(!sourceCode.includes('#c38b22'));});
 console.log('\n'+passed+' milestone checks passed. No system notifications shown.');
} finally {for(const off of cleanups.reverse())off();fs.rmSync(temp,{recursive:true,force:true});}
