import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import vm from 'node:vm';
process.env.DSH_NOTIFY_ALL_DRY_RUN = '1';
const { apply, DEFAULTS, Config } = await import('../lib/index.js');
let passed = 0;
const check = (label, fn) => { fn(); passed++; console.log('PASS ' + label); };
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'dsh-notify-regression-'));
const stateDir = path.join(temp, 'dsh-notify-all');
function host() {
  const routes = new Map(), events = new Map(), cleanups = [];
  const mutable = { ...DEFAULTS };
  const config = Object.fromEntries(Object.keys(mutable).map(k => [k, Object.freeze({ get: () => mutable[k] })]));
  const connection = { authenticatedUrl:u=>u+'?token=test', fetch:{register: r=> {routes.set(r.path,r);return()=>routes.delete(r.path);}} };
  const ctx = {fiber:{},connection,get:key=>({connection,profileContext:{home:temp},webServer:{port:12345}})[key],
    on:(event,fn)=>{events.set(event,fn); const off=()=>events.delete(event);cleanups.push(off);return off;},
    effect:fn=>{const off=fn();if(typeof off==='function')cleanups.push(off);return off;},inject:()=>{}};
  apply(ctx,config);
  const fire=(sid,type,data,seq)=>events.get('session/event')({id:sid,header:{parentSession:sid==='child'?'a':undefined}},{type,data,seq});
  const request=async(action,body)=>{
    const r=routes.get('/api/dsh-notify-all/'+action);assert.ok(r);
    const method=body===undefined?'GET':'POST'; assert.ok(r.methods.includes(method));
    const res=await r.fetch(new Request('http://localhost/api/dsh-notify-all/'+action,{method,...body===undefined?{}:{body:JSON.stringify(body)}}));
    return {code:res.status, data:await res.json()};
  };
  return {fire,request,mutable,events,dispose:()=>cleanups.reverse().forEach(fn=>fn())};
}
let app=host();
const readState=()=>JSON.parse(fs.readFileSync(path.join(stateDir,'state.json')));
const readUnread=()=>readState().unread.reduce((n,row)=>n+row[1],0);
const end=(sid,seq,kind='completed')=>app.fire(sid,'turn/end',{reason:{kind}},seq);
const viewer=(sid,focused=true,clientId='desktop')=>app.request('viewer',{sessionId:sid,focused,clientId});
await viewer('a');
app.fire('b','user/message',{source:{kind:'user'}});
end('b',1);
check('last typed session cannot hide completion in another conversation',()=>assert.equal(fs.readFileSync(path.join(stateDir,'badge.json'),'utf8').includes('"count":1'),true));
end('a',1);
check('visible session completion does not add unread',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,1));
end('b',1);
check('same durable event is deduplicated across Session object identities',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,1));
await viewer('b');
check('opening exactly one session clears only its unread items',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,0));
await viewer(null,false);
end('a',2);end('b',2);
await viewer('a');
check('other unread sessions survive focus and session switch',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,1));
await app.request('clear',{});
const ask=(sid,id)=>app.fire(sid,'tool/call',{name:'ask_user_question',callId:id,arguments:JSON.stringify({questions:[{question:'choose?'}]})});
ask('b','q1');ask('b','q1');
check('duplicate question events count once',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,1));
end('b',3,'blocked');
check('blocked turn during question does not double count',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,1));
app.fire('b','tool/result',{message:{toolCallId:'q1',content:[{type:'text',text:'{"pending":true}'}]}});
check('timed question remains pending after timeout',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,1));
await viewer('b');
check('viewing a question does not pretend it was answered',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,1));
app.fire('b','user/message',{source:{kind:'user-question-reply',callId:'q1'}});
check('late reply settles its question',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,0));
ask('b','q-recovery');
app.fire('b','tool/result',{message:{toolCallId:'q-recovery',isError:true,content:[]},error:{code:'TOOL_OUTCOME_UNKNOWN'}});
check('unknown tool outcome preserves answerable question',()=>assert.equal(readState().waits.length,1));
app.fire('b','user/message',{source:{kind:'user-question-reply',callId:'q-recovery'}});
const ptc={name:'ask_user_question',subCallId:'ptc-q',arguments:{questions:[{question:'PTC choice?'}]},content:[{type:'text',text:'{"pending":true}'}]};
app.fire('b','tool/ptc-dispatch',{...ptc,isError:true});
check('failed PTC question does not become pending',()=>assert.equal(readState().waits.length,0));
app.fire('b','tool/ptc-dispatch',{...ptc,content:[{type:'text',text:'{"answers":[]}'}]});
check('already answered PTC question does not become pending',()=>assert.equal(readState().waits.length,0));
app.fire('b','tool/ptc-dispatch',ptc);
check('pending PTC question uses its own sub-call id',()=>assert.equal(readState().waits[0][0],'b:ptc-q'));
app.fire('b','user/message',{source:{kind:'user-question-reply',callId:'ptc-q'}});
check('late PTC reply clears its pending count',()=>assert.equal(readState().waits.length,0));
app.fire('b','approval/asked',{id:'approve',toolName:'shell'});app.fire('b','approval/asked',{id:'approve',toolName:'shell'});
app.fire('b','approval/decided',{id:'approve'});
check('approval decision settles its unique request',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,0));
app.fire('b','tool/call',{name:'exit_plan_mode',callId:'plan',arguments:'{"plan":"# Plan"}'});
app.fire('b','tool/result',{message:{toolCallId:'plan',content:[{type:'text',text:'approved'}]}});
check('plan result settles its request',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,0));
ask('child','qchild');end('child',1);
check('child questions and completions are excluded by default',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,0));
app.mutable.question=false;ask('b','q2');
check('turning off question toast keeps pending badge accurate',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,1));
await app.request('clear',{});
check('mark all read never clears unanswered requests',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,1));
end('b',4,'aborted');
check('aborted turn removes abandoned waits',()=>assert.equal(readState().waits.length,0));
await viewer(null,false);app.mutable.toastsEnabled=false;end('a',5);
check('notifications disabled still counts taskbar unread',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,1));
app.mutable.badgeColor='black';app.events.get('loader/volatile-update')();
check('volatile settings immediately redraw native badge',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).color,'#1A1A1A'));
app.mutable.enabled=false;app.events.get('loader/volatile-update')();end('a',6);
check('disabled plugin ignores new events and hides native badge',()=>assert.equal(JSON.parse(fs.readFileSync(path.join(stateDir,'badge.json'))).count,0));
app.mutable.enabled=true;app.mutable.toastsEnabled=true;
const logPath=path.join(stateDir,'log.txt'),before=fs.readFileSync(logPath,'utf8');
end('b',5);
check('first completion toast is immediate in dry-run',()=>assert.ok(fs.readFileSync(logPath,'utf8').slice(before.length).includes('toast dry-run completion')));
app.dispose();
check('host unload removes all routes and events',()=>assert.equal(app.events.size,0));
app=host();
check('unread state survives host reload',()=>assert.equal(readUnread(),2));
end('b',5);
check('reload preserves durable event deduplication',()=>assert.equal(readUnread(),2));
await viewer('a');
check('same-titled conversations are separated by exact session id',()=>assert.equal(readUnread(),1));
const invalid=await app.request('viewer',{sessionId:3,focused:true,clientId:'bad'});
check('invalid viewer payload is rejected',()=>assert.equal(invalid.code,400));
const realNow=Date.now; let clock=realNow();Date.now=()=>clock;
await viewer('b');clock+=6100;end('b',6);Date.now=realNow;
check('expired focus report cannot suppress unread',()=>assert.equal(readUnread(),1));
check('Config is complete and volatile',()=>assert.ok(Object.values(Config.dict).every(x=>x.meta.volatile)));
check('invalid badge color fails schema validation',()=>assert.throws(()=>Config({badgeColor:'blue'})));
const activationSid='session-00000000-0000-4000-8000-000000000001';
const key=fs.readFileSync(path.join(stateDir,'activation-key.txt'),'utf8');
const activationInbox=path.join(stateDir,'activation-inbox');
fs.writeFileSync(path.join(activationInbox,'0'.repeat(32)+'.uri'),'dsh-notify-all://open?key=wrong&session='+activationSid);
const rejected=(await app.request('activation',{clientId:'native-client'})).data;
check('untrusted protocol activation is rejected',()=>assert.equal(rejected.activation,null));
check('invalid activation file does not clear unread',()=>assert.equal(readUnread(),1));
const activationId='1'.repeat(32);
fs.writeFileSync(path.join(activationInbox,activationId+'.uri'),'dsh-notify-all://open?key='+key+'&session='+activationSid);
const accepted=(await app.request('activation',{clientId:'native-client'})).data;
check('notification click carries exact target conversation',()=>assert.equal(accepted.activation.sessionId,activationSid));
await viewer('b');
check('toast focus cannot mark the previously visible conversation as read',()=>assert.equal(readUnread(),1));
await app.request('activation',{clientId:'native-client',ack:'wrong'});
const retained=(await app.request('activation',{clientId:'native-client'})).data;
check('failed navigation cannot acknowledge another activation',()=>assert.equal(retained.activation.id,activationId));
const acknowledged=(await app.request('activation',{clientId:'native-client',ack:activationId})).data;
check('successful navigation acknowledges only its own click',()=>assert.equal(acknowledged.activation,null));
await viewer('b');
check('late focus reports after navigation cannot clear unrelated unread',()=>assert.equal(readUnread(),1));
const fenceClock=Date.now;Date.now=()=>fenceClock()+2600;
await viewer('b');Date.now=fenceClock;
check('navigation fence expires so later ordinary views still clear unread',()=>assert.equal(readUnread(),0));
app.dispose();

// Run the actual module factory, with public service-shaped observable sources.
let exported;
const requests=[], subscriptions=[], disposers=[], listeners=[];
const source=value=>({value,getSnapshot(){return this.value;},subscribe(fn){subscriptions.push(fn);return()=>subscriptions.splice(subscriptions.indexOf(fn),1);}});
const current=source({key:'b'}),panel=source({activePanelId:null}),list=source({byId:{b:{id:'b',title:'same title'}}});
const fakeTarget={addEventListener:(n,fn)=>listeners.push([n,fn]),removeEventListener:(n,fn)=>listeners.splice(listeners.findIndex(x=>x[0]===n&&x[1]===fn),1)};
const intervals=new Set();
const sandbox={window:{...fakeTarget,__ModuleLoader__:{load:row=>{exported=row.factory(id=>{assert.equal(id,'react');return {};});}}},
  document:{...fakeTarget,hidden:false,hasFocus:()=>true},crypto:{randomUUID:()=> 'test-client'},
  fetch:async(url,init)=>{requests.push([url,init]);return{ok:true,json:async()=>({})};},
  setInterval:fn=>{intervals.add(fn);return fn;},clearInterval:fn=>intervals.delete(fn),setTimeout,clearTimeout,AbortController,Date,Math};
vm.runInNewContext(fs.readFileSync(new URL('../lib/client.js',import.meta.url),'utf8'),sandbox);
const tracker=exported.trackViewer({uiSession:{current},layout:{panelInfo:panel},sessions:{list},effect:fn=>disposers.push(fn()),on:()=>{}});
await new Promise(r=>setImmediate(r));
check('client reports exact id from public UiSession binding',()=>assert.equal(JSON.parse(requests[0][1].body).sessionId,'b'));
check('ordinary web client cannot claim desktop focus',()=>assert.equal(JSON.parse(requests[0][1].body).desktop,false));
panel.value={activePanelId:'settings'};subscriptions.forEach(fn=>fn());await new Promise(r=>setImmediate(r));
check('settings panel does not mark hidden conversation as viewed',()=>assert.equal(JSON.parse(requests.at(-1)[1].body).sessionId,null));
panel.value={activePanelId:null};current.value={key:'a'};subscriptions.forEach(fn=>fn());await new Promise(r=>setImmediate(r));
check('session changes report without clicking DOM text',()=>assert.equal(JSON.parse(requests.at(-1)[1].body).sessionId,'a'));
check('session switch advances viewer revision',()=>assert.equal(JSON.parse(requests.at(-1)[1].body).viewEpoch,1));
tracker.setCovered(true);await new Promise(r=>setImmediate(r));
check('native settings dialog cannot mark covered conversation as read',()=>assert.equal(JSON.parse(requests.at(-1)[1].body).sessionId,null));
check('settings cover preserves selected session and revision',()=>{const v=JSON.parse(requests.at(-1)[1].body);assert.equal(v.selectedSessionId,'a');assert.equal(v.viewEpoch,1);});
tracker.setCovered(false);await new Promise(r=>setImmediate(r));
check('closing native settings resumes the current conversation report',()=>assert.equal(JSON.parse(requests.at(-1)[1].body).sessionId,'a'));
current.value={key:'b'};subscriptions.forEach(fn=>fn());current.value={key:'a'};subscriptions.forEach(fn=>fn());await new Promise(r=>setImmediate(r));
check('coalesced leave-and-return keeps an advanced revision',()=>assert.equal(JSON.parse(requests.at(-1)[1].body).viewEpoch,3));
sandbox.window.dshDesktop={protocolVersion:1};subscriptions.forEach(fn=>fn());await new Promise(r=>setImmediate(r));
check('native preload identifies the desktop viewer report',()=>assert.equal(JSON.parse(requests.at(-1)[1].body).desktop,true));
disposers.reverse().forEach(fn=>fn());
check('client unload clears timers, subscriptions and event listeners',()=>{assert.equal(intervals.size,0);assert.equal(subscriptions.length,0);assert.equal(listeners.length,0);});
check('no body injection or floating pill remains',()=>assert.ok(!fs.readFileSync(new URL('../lib/client.js',import.meta.url),'utf8').includes('appendChild')));
const activationRequests=[],navigation=[],activationCleanups=[];
let click={id:'clicked',sessionId:activationSid};
sandbox.window.dshDesktop={protocolVersion:1};sandbox.location={hash:'',pathname:'/',search:''};
sandbox.fetch=async(url,init)=>{const body=JSON.parse(init.body);activationRequests.push(body);if(body.ack)click=null;return{ok:true,json:async()=>({activation:click})};};
let closed=0;
exported.trackActivation({uiWorkspace:{openSession:id=>{navigation.push(id);current.value={key:id};}},uiSession:{current},
  effect:fn=>activationCleanups.push(fn()),on:()=>{}},{closeSettings:()=>closed++,setError:()=>{}});
await new Promise(r=>setImmediate(r));
check('click opens conversation through official uiWorkspace operation',()=>assert.equal(navigation[0],activationSid));
check('notification closes its settings page before revealing conversation',()=>assert.equal(closed,1));
check('client acknowledges only after target binding is selected',()=>assert.equal(activationRequests.at(-1).ack,'clicked'));
activationCleanups.forEach(fn=>fn());
check('activation polling unloads without timers or focus listeners',()=>{assert.equal(intervals.size,0);assert.equal(listeners.length,0);});
console.log('\n' + passed + ' regression checks passed. No system notifications shown.');
fs.rmSync(temp,{recursive:true,force:true});
